// <auto-generated />
namespace BeautySalon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ServiceSubtypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ServiceSubtypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201802181551000_ServiceSubtypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
